name: bilibili
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # 网络
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.1.0

  # 视频播放器
  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4
  # 存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  # 媒体通知
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  # 动态取色
  dynamic_color: ^1.7.0

  get: ^4.6.6

  # 弹幕
  ns_danmaku:
    git:
      url: https://github.com/guozhigq/flutter_ns_danmaku.git
      ref: master
  # 音量、亮度、屏幕控制
  flutter_volume_controller: ^1.3.2
  screen_brightness: ^0.2.2+1
  universal_platform: ^1.1.0
  # 进度条
  auto_orientation: ^2.3.1
  audio_video_progress_bar: ^2.0.3
  protobuf: ^3.1.0
  # toast
  flutter_smart_dialog: ^4.9.8+3
  # 获取appx信息
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  # 设备信息
  device_info_plus: ^9.0.0
  # 权限
  permission_handler: ^11.3.0
  # 加密
  crypto: ^3.0.6
  encrypt: ^5.0.3
  # 防抖节流
  easy_debounce: ^2.0.3
  # 状态栏图标控制
  status_bar_control: ^3.2.1
  # 极验
  gt3_flutter_plugin: ^0.1.0
  uuid: ^4.5.1
  scrollable_positioned_list: ^0.3.8
  logger: ^2.3.0
  catcher_2: ^1.2.6
  path: ^1.9.0
  # scheme跳转
  appscheme: ^1.0.8
  # 高帧率
  flutter_displaymode: ^0.6.0
  # 图片
  cached_network_image: ^3.4.1
  extended_image: ^8.2.0
  saver_gallery: ^3.0.1
  # 二维码
  qr_flutter: ^4.1.0
  # cookie 管理
  webview_cookie_manager: ^2.0.6
  # 浏览器
  webview_flutter: ^4.10.0
  # 分享
  share_plus: ^10.1.1
  # 上拉加载
  loading_more_list: ^7.1.0
  # 下拉刷新
  pull_to_refresh_notification: ^3.1.0
  # 图标
  font_awesome_flutter: ^10.7.0
  # 下滑关闭
  custom_sliding_segmented_control: ^1.8.3
  dismissible_page: ^1.0.2
  # html解析
  html: ^0.15.4
  # html渲染
  flutter_html: ^3.0.0-beta.2
  # pip
  floating:
    git:
      url: https://github.com/guozhigq/floating.git
      ref: main
  # 投屏
  dlna_dart: ^0.0.8
  lottie: ^3.1.2
  # 解决sliver滑动不同步
  extended_nested_scroll_view: ^6.2.1
  # 电池优化
  disable_battery_optimization: ^1.1.1
  # 展开/收起
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# dependency_overrides:
#   media_kit:
#     git:
#       url: https://github.com/media-kit/media-kit
#       path: media_kit
#   media_kit_video:
#     git:
#       url: https://github.com/media-kit/media-kit
#       path: media_kit_video
#   media_kit_libs_video:
#     git:
#       url: https://github.com/media-kit/media-kit
#       path: libs/universal/media_kit_libs_video

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo/logo_android_2.png
  image_path_android: assets/images/logo/logo_android_2.png
  image_path_ios: assets/images/logo/logo_ios.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo/logo_android_2.png
  adaptive_icon_monochrome: assets/images/logo/logo_android_2.png
  macos:
    generate: true
    image_path: assets/images/logo/logo_ios.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/lv/
    - assets/images/logo/
    - assets/images/live/
    - assets/images/video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: fansCard
      fonts:
        - asset: assets/fonts/fansCard.ttf
    - family: Jura-Bold
      fonts:
        - asset: assets/fonts/Jura-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
